name = "SingularSpectrumAnalysis"
uuid = "d9d29d28-c116-5dba-9239-57a5fe2387ff"
author = "Fredrik Bagge Carlson <baggepinnen@gmail.com>"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
